---

- name: Install immich asset backups script
  ansible.builtin.template:
    src: "{{ immich_assets_backup_script_template_name }}"
    dest: "{{ immich_assets_backup_scripts_path }}"
    owner: "{{ homelab_user }}"
    group: "{{ homelab_user }}"
    mode: '0744'
