---
- name: Add homelab user
  ansible.builtin.user:
    name: "{{ homelab_user }}"
    shell: /bin/bash
    create_home: true

- name: Ensure homelab user directories are created
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
    owner: "{{ homelab_user }}"
    group: "{{ homelab_user }}"
  loop: "{{ homelab_user_dirs }}"

- name: Add sftp_user
  ansible.builtin.user:
    name: "{{ sftp_user }}"
    shell: /bin/bash
    create_home: true

- name: Add read rights to sftp user home directory
  ansible.builtin.file:
    path: "~{{ sftp_user }}"
    mode: "0755"

- name: Ensure homelab user is part of sftp group
  ansible.builtin.user:
    name: "{{ homelab_user }}"
    groups: "{{ sftp_user }}"
    append: true
