---
- name: Install KVM and libvirt packages.
  ansible.builtin.apt:
    name: "{{ kvm_packages }}"
    state: "{{ kvm_packages_state }}"
    install_recommends: false

- name: Ensure {{ homelab_user }} user is part of libvirt group.
  user:
    name: "{{ homelab_user }}"
    groups: libvirt
    append: true

- name: Install vagrant.
  ansible.builtin.apt:
    name: "{{ vagrant_packages }}"
    state: "{{ vagrant_packages_state }}"
